"""initial migrations

Revision ID: e08530a830d4
Revises: 
Create Date: 2025-01-21 09:52:36.045564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e08530a830d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('discount_price', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('(discount_price is NULL) or (discount_price < price)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_products_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_lifts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lift_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lift_id'], ['lifts.id'], name=op.f('fk_user_lifts_lift_id_lifts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_lifts_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'lift_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_lifts')
    op.drop_table('products')
    op.drop_table('users')
    op.drop_table('lifts')
    # ### end Alembic commands ###
